#!/bin/bash

git init
git add .
git commit -m "simple rendering from img"
git config --global user.email "zako0808@gmail.com"
git config --global user.name "TakashiSugie"
git remote rm origin
git remote add origin https://github.com/TakashiSugie/GLtest.git
git push -u origin simple
